### ISSUE TITLE
About source code history

### ISSUE THREAD

**Issue by FabioLolix** [proh14/ptext#10]
Hello @proh14, I have seen about ptext some days ago on twitter

> ptext is a text editor based on kilo. 

Would be nice when you base your work on other people work to maintain the license and code history instead of squashing or cherry picking files, github have the option to `import` a repository if you want to make a detached fork from the start

I see you have restored the BSD license to which you should add you 2023 copyright below Antirez one

**Comment by proh14** [comment]
Hello @FabioLolix. Thank you for the suggestion. I'm going to stay with the cherry-picking part because it is completely legal and I mentioned kilo 3 times in the readme plus the license is ok too. (If I am wrong tell me) But I will surely add my license notice to it! If that sounds good I can close the issue. (By the way. I would like to know which account announced it on Twitter.)

**Comment by proh14** [comment]
Check #11

**Comment by proh14** [comment]
#11
